require "pry"
require "json"
require "rest-client"
require "colorize"
require "tty-link"

require "./lib/swstarships/cli"
require "./lib/swstarships/api"
require "./lib/swstarships/starship"
require "./lib/swstarships/version"
